import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='top-0'>
          <ul>
            <li>Elevador</li>
            <li>Cocpit</li>
            <li>Conecção</li>
          </ul>
        </nav>
        {children}
        <nav className='bottom-0'>
          <ul>
            <li>Hub</li>
            <li>Reator</li>
            <li>Ancora</li>
          </ul>
        </nav>
      </body>
    </html>
  )
}
